// <auto-generated />
using System;
using Fiap.Banco.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Banco.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519232926_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Banco.API.Models.Campeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Temporada")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("NVARCHAR2(21)");

                    b.HasKey("Id");

                    b.ToTable("CAMPEONATOS");

                    b.HasDiscriminator<string>("Tipo").HasValue("Base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Estatistica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Derrotas")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Empates")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("GolsContra")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("GolsPro")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Pontos")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TimeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Vitorias")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("TimeId", "CampeonatoId")
                        .IsUnique();

                    b.ToTable("ESTATISTICAS");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataPartida")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("GolsCasa")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("GolsVisitante")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TimeCasaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TimeVisitanteId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("TimeCasaId");

                    b.HasIndex("TimeVisitanteId");

                    b.ToTable("PARTIDAS");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.HasKey("Id");

                    b.ToTable("PESSOAS");

                    b.HasDiscriminator<string>("Tipo").HasValue("Pessoa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoFundacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("TIMES");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.TimeCampeonato", b =>
                {
                    b.Property<int>("TimeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("TimeId", "CampeonatoId");

                    b.HasIndex("CampeonatoId");

                    b.ToTable("TIMES_CAMPEONATOS");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Trofeu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("TimeId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.ToTable("TROFEUS");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.CampeonatoPontosCorridos", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Campeonato");

                    b.Property<bool>("ConfrontosGerados")
                        .HasColumnType("BOOLEAN");

                    b.Property<int>("TotalRodadas")
                        .HasColumnType("NUMBER(10)");

                    b.ToTable("CAMPEONATOS");

                    b.HasDiscriminator().HasValue("PontosCorridos");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Jogador", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Pessoa");

                    b.Property<int>("NumeroCamisa")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("TimeId")
                        .HasColumnType("NUMBER(10)");

                    b.HasIndex("TimeId");

                    b.ToTable("PESSOAS");

                    b.HasDiscriminator().HasValue("Jogador");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Tecnico", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Pessoa");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("TimeId")
                        .HasColumnType("NUMBER(10)");

                    b.HasIndex("TimeId");

                    b.ToTable("PESSOAS", t =>
                        {
                            t.Property("TimeId")
                                .HasColumnName("Tecnico_TimeId");
                        });

                    b.HasDiscriminator().HasValue("Tecnico");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Estatistica", b =>
                {
                    b.HasOne("Fiap.Banco.API.Models.Campeonato", "Campeonato")
                        .WithMany()
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Banco.API.Models.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Partida", b =>
                {
                    b.HasOne("Fiap.Banco.API.Models.Campeonato", "Campeonato")
                        .WithMany("Partidas")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Banco.API.Models.Time", "TimeCasa")
                        .WithMany()
                        .HasForeignKey("TimeCasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fiap.Banco.API.Models.Time", "TimeVisitante")
                        .WithMany()
                        .HasForeignKey("TimeVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("TimeCasa");

                    b.Navigation("TimeVisitante");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.TimeCampeonato", b =>
                {
                    b.HasOne("Fiap.Banco.API.Models.Campeonato", "Campeonato")
                        .WithMany("Times")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Banco.API.Models.Time", "Time")
                        .WithMany("Campeonatos")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Trofeu", b =>
                {
                    b.HasOne("Fiap.Banco.API.Models.Time", "Time")
                        .WithMany("Trofeus")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Jogador", b =>
                {
                    b.HasOne("Fiap.Banco.API.Models.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Tecnico", b =>
                {
                    b.HasOne("Fiap.Banco.API.Models.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Campeonato", b =>
                {
                    b.Navigation("Partidas");

                    b.Navigation("Times");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Time", b =>
                {
                    b.Navigation("Campeonatos");

                    b.Navigation("Trofeus");
                });
#pragma warning restore 612, 618
        }
    }
}
